plugins:
  - jekyll-paginate

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Pavel Korolev'
tagline:          'Borodust Webpage'
description:      'Aware software engineer'
url:              https://borodust.org
name:             Boroblog

author:
  name:           'Pavel Korolev'
  email:          mail@borodust.org
  url:            https://github.com/borodust

paginate:         5

# Custom vars
borodust:
  github:        https://github.com/borodust
  twitter:       https://twitter.com/borodust
  mastodon:      https://mastodon.social/@borodust
  keybase:       https://keybase.io/borodust/
