# Gems
gems:
  - jekyll-paginate

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Pavel Korolev'
tagline:          'Borodust Webpage'
description:      'Aware software developer'

author:
  name:           'Pavel Korolev'
  email:          mail@borodust.org
  url:            https://github.com/borodust

paginate_path:    /blog/page:num/
paginate:         5

# Custom vars
borodust:
  github:        https://github.com/borodust
  twitter:       https://twitter.com/borodust
  facebook:      https://facebook.com/borodust
